// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvjbquiyhxnqmagvxvxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2amJxdWl5aHhucW1hZ3Z4dnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTM5MDAsImV4cCI6MjA3NDMyOTkwMH0.yEZDrnAhMCG-mqNJM64lbwFczZVmAZRC-aTjkJLKr-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});